### ISSUE TITLE
Any example for Windows users?

### ISSUE THREAD

**Issue by horacehylee** [gokrazy/rsync#30]
Thanks for this awesome work!

May I ask if any Windows example?
As tried with `gokr-rsyncd --daemon --gokr.listen=localhost:8730 --gokr.modulemap=pwd=C:\Users\Public` and does not work with error of `unexpectedly able to write file`

**Comment by stapelberg** [comment]
I had some success with the following `rsyncd.toml`:

```toml
# safe with authorized ssh
dont_namespace = true

[[listener]]
  [listener.authorized_ssh]
    address = ":22873"
    authorized_keys = "authorized_keys.txt"

[[module]]
  name = "repro"
  path = "C:\\Users\\Michael Stapelberg\\rsyncpwd"
```

…and then starting `gokr-rsyncd.exe --daemon --gokr.config rsyncd.toml`

From my other machine, I could transfer the files in `rsyncpwd` using:

```
% cat >> ~/.ssh/config <<'EOT'
Host beast-windows-rsync
	Hostname beast.lan
	Port 22873
EOT

% rsync -av -e ssh rsync://beast-windows-rsync/repro /tmp/rep
receiving file list ... done
created directory /tmp/rep
./
C:\Users\Michael Stapelberg\rsyncpwd\exfiltrate.png

sent 117 bytes  received 279.055 bytes  558.344,00 bytes/sec
total size is 282.900  speedup is 1,01

% ls -l /tmp/rep
total 276K
-r--r--r-- 1 michael michael 273K 2019-09-20 19:41 'C:\Users\Michael Stapelberg\rsyncpwd\exfiltrate.png'
```

Note that the filename incorrectly contains the whole path. 

I expect that there are a number of smaller issues like that in the code base, as I don’t use Windows.

Improvements welcome.
